Final version of Matrix

diff --git a/matrix b/matrix
--- a/matrix
+++ b/matrix
@@ -43,12 +43,11 @@ transpose() {
     numWords=$(echo "$file" | wc -w)
     numCol=$(($numWords / $numRows))
 
-    #For each column of data, substitute newlines for tabs in that column
+    #For each column of data: using paste, substitute newlines for tabs in that column
     #and append a final newline character. This transforms columns into rows,
     #where column n becomes row n.
     for ((i = 1; i <= $numCol; i++)); do
-        echo -n "$file" | cut -f $i | tr '\n' '\t'
-        echo
+        echo "$file" | cut -f $i | paste -s
     done
 }
 
@@ -119,7 +118,7 @@ add() {
     #If matrices passed cannot be added due to mismatching dimensions
     #send error message to stderr and abort    
     elif [[ $(dims $1) != $(dims $2) ]]; then 
-        echo "Error: 'add' defined only for matrices with the same dimensions."
+        echo "Error: 'add' defined only for matrices with the same dimensions." 1>&2
         exit 1
     fi
     
@@ -166,6 +165,8 @@ getRows() {
 }
  
 multiply() {
+    #Ran out of time to comment this section
+
     if [[ $# != 2 ]]; then
         echo "Error: 'multiply' can accept just two arguments." 1>&2
         exit 1
@@ -184,30 +185,31 @@ multiply() {
     numW2=$(echo "$file2" | wc -w)
     numC2=$(($numW2 / $numR2))
 
-    if [[ $numC1 = $numC2 ]]; then
-        temp1="temp1$$"
-        temp2="temp2$$"
-        echo "$file1" > $temp1 
-        echo "$file2" > $temp2
-        while read -r line1; do
-                while read -r line2; do
-                   sum=0
-                   for ((i = 1; i <= $numC1; i++)); do 
-                        pair=$(echo -e "$line1\n$line2" | cut -f $i | tr '\n' '\t')
-                        prod=1
-                        for n in $pair; do
-                            ((prod*=n))
-                        done
-                        ((sum+=prod))
-                   done
+    temp1="temp1$$"
+    temp2="temp2$$"
+    echo "$file1" > $temp1 
+    echo "$file2" > $temp2
+    while read -r line1; do
+            count=0
+            while read -r line2; do
+               ((count++))
+               sum=0
+               for ((i = 1; i <= $numC1; i++)); do 
+                    pair=$(echo -e "$line1\n$line2" | cut -f $i | paste -s)
+                    prod=1
+                    for n in $pair; do
+                        ((prod*=n))
+                    done
+                    ((sum+=prod))
+               done
+               if [[ $count = $numR2 ]]; then
+                   echo "sum"
+               else    
                    echo -ne "$sum\t"
-                done < $temp2
-                echo
-        done < $temp1
-        rm $temp1 $temp2
-    else
-        echo "nope"
-    fi
+               fi    
+            done < $temp2
+    done < $temp1
+    rm $temp1 $temp2
 }
 
 validate() {
